### ISSUE TITLE
MIB3 Support this feature

### ISSUE THREAD

**Issue by nirvananils** [adi961/mib2-android-auto-vc#11]
Maybe you can use some MIB3 Binaries, as the MOI3 Units for MQB Classik cars support this feature

**Comment by adi961** [comment]
I am pretty sure that is not possible since MIB2 is QNX based and MIB3 is ARM I think. So the binaries cannot run on the architecture

**Comment by nirvananils** [comment]
Indeed forgot the MIB3 is running AGL Linux and not QNX
