### ISSUE TITLE
MIB2.5 no navy support

### ISSUE THREAD

**Issue by kapustor** [adi961/mib2-android-auto-vc#5]
Hi @adi961, thank you for this great project!

I have VW with unit `MST2_EU_VW_P0876D` (D for Delphi?), no navy, new-look digital dashboard (see photo). Should this work for me? I doubt that the navy suggestions will work since there is no navy in the headunit, but at least track info?

![image](https://github.com/user-attachments/assets/76c2487b-2403-441a-bc6c-c48e80c5a9d7)

![image](https://github.com/user-attachments/assets/a79df457-063a-4089-82ee-b6b67aebf182)

**Comment by OneB1t** [comment]
There will be way to show navigation data as text messages or inside music data.

**Comment by kapustor** [comment]
@OneB1t this feature is already release or will be released in future? Also, is my unit type supported?

**Comment by adi961** [comment]
@kapustor The patch is designed for MIB2 High. You have a MIB STD. But if you can send me your lsd.jxe (you can extract it using mib2-toolbox) I can take a look if there is anything I can do to make it work.
